import { User, Role, Dish } from './types';

export const DUMMY_USERS: User[] = [
    { id: 1, name: 'Alice Customer', email: 'customer@example.com', role: Role.CUSTOMER, phone: '123-456-7890', address: '123 Maple St, Springfield' },
    { id: 2, name: 'Bob Staff', email: 'staff@example.com', role: Role.STAFF, phone: '234-567-8901', address: '456 Oak Ave, Shelbyville' },
    { id: 3, name: 'Janani Sree', email: 'admin@example.com', role: Role.ADMIN, phone: '345-678-9012', address: '789 Pine Ln, Capital City' },
    { id: 4, name: 'Hari', email: 'superadmin@example.com', role: Role.SUPERADMIN, phone: '456-789-0123', address: '101 Main Blvd, Metropolis' },
    { id: 5, name: 'Edward Manager', email: 'manager@example.com', role: Role.ADMIN, phone: '567-890-1234', address: '212 Elm Rd, Gotham' },
    { id: 6, name: 'Fiona Guest', email: 'guest@example.com', role: Role.CUSTOMER, phone: '678-901-2345', address: '323 Birch Ct, Star City' },
    { id: 7, name: 'George Cook', email: 'cook@example.com', role: Role.STAFF, phone: '789-012-3456', address: '434 Cedar Pl, Central City' },
    { id: 8, name: 'Hannah Moderator', email: 'moderator@example.com', role: Role.ADMIN, phone: '890-123-4567', address: '545 Spruce Way, Coast City' },
    { id: 9, name: 'Ian Support', email: 'support@example.com', role: Role.STAFF, phone: '901-234-5678', address: '656 Willow Dr, Fawcett City' },
    { id: 10, name: 'Julia Client', email: 'client@example.com', role: Role.CUSTOMER, phone: '012-345-6789', address: '767 Aspen Ave, Keystone City' },
    { id: 11, name: 'Kevin Waiter', email: 'waiter@example.com', role: Role.STAFF, phone: '112-233-4455', address: '878 Fir St, Midway City' },
    { id: 12, name: 'Laura SecAdmin', email: 'secadmin@example.com', role: Role.SUPERADMIN, phone: '223-344-5566', address: '989 Redwood Blvd, Bludhaven' },
];

export const DUMMY_MENU: Dish[] = [
    {
        id: 1,
        name: 'Quinoa & Avocado Salad',
        description: 'A vibrant mix of organic quinoa, avocado, cherry tomatoes, and a zesty lemon-tahini dressing. A healthy and refreshing starter.',
        price: 1160,
        category: 'Appetizer',
        imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=870&auto=format&fit=crop',
        rating: 4.8,
        reviews: 125,
    },
    {
        id: 2,
        name: 'Grilled Salmon Steak',
        description: 'Perfectly grilled salmon fillet with a citrus glaze, served with asparagus and roasted potatoes.',
        price: 2240,
        category: 'Main Course',
        imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?q=80&w=870&auto=format&fit=crop',
        rating: 4.9,
        reviews: 210,
    },
    {
        id: 3,
        name: 'Savory Ramen Noodles',
        description: 'A delicious bowl of handmade noodles in a savory broth, topped with tender pork belly, a soft-boiled egg, and fresh scallions.',
        price: 1820,
        category: 'Main Course',
        imageUrl: 'https://images.unsplash.com/photo-1552611052-33e04de081de?q=80&w=764&auto=format&fit=crop',
        rating: 4.7,
        reviews: 180,
    },
    {
        id: 4,
        name: 'Chocolate Lava Cake',
        description: 'A decadent chocolate cake with a molten lava center, served with a scoop of vanilla bean ice cream and a raspberry coulis.',
        price: 960,
        category: 'Dessert',
        imageUrl: 'https://images.unsplash.com/photo-1586985289936-e04c07238918?q=80&w=774&auto=format&fit=crop',
        rating: 5.0,
        reviews: 350,
    },
    {
        id: 5,
        name: 'Classic Tomato Bruschetta',
        description: 'Toasted artisan bread topped with a mix of fresh tomatoes, garlic, basil, and a drizzle of balsamic glaze.',
        price: 900,
        category: 'Appetizer',
        imageUrl: 'https://images.unsplash.com/photo-1505253716362-afb54249332f?q=80&w=870&auto=format&fit=crop',
        rating: 4.6,
        reviews: 95,
    },
    {
        id: 6,
        name: 'Chicken Caesar Salad',
        description: 'Crisp romaine lettuce, parmesan cheese, and crunchy croutons tossed in our signature Caesar dressing. Topped with grilled chicken.',
        price: 1200,
        category: 'Appetizer',
        imageUrl: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?q=80&w=870&auto=format&fit=crop',
        rating: 4.5,
        reviews: 150,
    },
    {
        id: 7,
        name: 'Prime Ribeye Steak',
        description: 'A 12oz prime ribeye steak, cooked to perfection, served with a side of garlic mashed potatoes and seasonal vegetables.',
        price: 3640,
        category: 'Main Course',
        imageUrl: 'https://images.unsplash.com/photo-1551028150-64b9f398f67b?q=80&w=870&auto=format&fit=crop',
        rating: 4.9,
        reviews: 250,
    },
    {
        id: 8,
        name: 'Fresh Mint Mojito',
        description: 'A refreshing blend of white rum, fresh mint, lime juice, sugar, and a splash of soda water. The perfect cocktail.',
        price: 1040,
        category: 'Beverage',
        imageUrl: 'https://images.unsplash.com/photo-1604323223639-2a0914f6b0b2?q=80&w=774&auto=format&fit=crop',
        rating: 4.8,
        reviews: 88,
    },
     {
        id: 9,
        name: 'Italian Tiramisu',
        description: 'Classic Italian dessert with layers of coffee-soaked ladyfingers and creamy mascarpone, dusted with cocoa powder.',
        price: 920,
        category: 'Dessert',
        imageUrl: 'https://images.unsplash.com/photo-1571683407094-c14b5397a688?q=80&w=774&auto=format&fit=crop',
        rating: 4.9,
        reviews: 190,
    },
];